service: media-gallery
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /static
  static_dir: static

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest

env_variables:
  WIX_BUCKET_NAME: media-gallery-dot-wixgamma
  WIX_DATABASE_NAME: media-gallery-dot-wixgamma
